set search_path = co;
create table orders (
	order_id bigint generated by default as identity (start with 1951 increment by 1 ),
	order_datetime timestamp not null,
	customer_id bigint not null,
	order_status varchar(10) not null,
	store_id bigint not null
) ;
comment on table orders is e'details of who made purchases where';
comment on column orders.order_datetime is e'when the order was placed';
comment on column orders.order_status is e'what state the order is in. valid values are:
open - the order is in progress
paid - money has been received from the customer for this order
shipped - the products have been dispatched to the customer
complete - the customer has received the order
cancelled - the customer has stopped the order
refunded - there has been an issue with the order and the money has been returned to the customer';
comment on column orders.customer_id is e'who placed this order';
comment on column orders.store_id is e'where this order was placed';
comment on column orders.order_id is e'auto-incrementing primary key';
