set search_path = co;
create table stores (
	store_id bigint generated by default as identity (start with 24 increment by 1 ),
	store_name varchar(255) not null,
	web_address varchar(100),
	physical_address varchar(512),
	latitude bigint,
	longitude bigint,
	logo bytea,
	logo_mime_type varchar(512),
	logo_filename varchar(512),
	logo_charset varchar(512),
	logo_last_updated timestamp
) ;
comment on table stores is e'physical and virtual locations where people can purchase products';
comment on column stores.store_name is e'what the store is called';
comment on column stores.logo_mime_type is e'the mime-type of the store logo';
comment on column stores.logo_last_updated is e'the date the image was last changed';
comment on column stores.longitude is e'the east-west position of a physical store';
comment on column stores.latitude is e'the north-south position of a physical store';
comment on column stores.logo is e'an image used by this store';
comment on column stores.web_address is e'the url of a virtual store';
comment on column stores.physical_address is e'the postal address of this location';
comment on column stores.store_id is e'auto-incrementing primary key';
comment on column stores.logo_filename is e'the name of the file loaded in the image column';
comment on column stores.logo_charset is e'the character set used to encode the image';
alter table stores add primary key (store_id);
alter table stores add unique (store_name);
alter table stores add constraint store_at_least_one_address_c check (
    coalesce( web_address, physical_address ) is not null
);
